import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import bg from "../../public/Images/image.webp"
import Image from 'next/image'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full h-screen relative ">
          <Image
            src={bg}
            alt="Background Image"
            layout="fill"
            objectFit="cover"
          />
          {children}
        </div>


      </body>
    </html>
  )
}
